import "../styles/globals.css";
import { PlasmicRootProvider } from "@plasmicapp/react-web";

let a = {
  event_type: "plasmic-to-dev",
  client_payload: {
    data: {
      branch: "main",
      project_id: "2kS349DKMK4UC7Q38aQg2a",
      project_api_token:
        "xuIWfnHx7V5uN3gcr4ld7bZR1MyrVvp3O4lSdh6aFL9ywEMIsxRT8ydba0Jt1hCQQTCv8jLoZwnugAuxjxuA",
      platform: "nextjs",
      language: "ts",
      scheme: "codegen",
      title: "[plasmic-to-dev] Sync project",
      description:
        "This is an automated commit generated by Hector Cuevas using Plasmic (https://plasmic.app/).",
    },
  },
};

function MyApp({ Component, pageProps }) {
  return (
    <PlasmicRootProvider>
      <Component {...pageProps} />
    </PlasmicRootProvider>
  );
}

export default MyApp;
