# Plasmic workflow v3
name: Build produdction app and store build

on: workflow_dispatch

jobs:
  job:
    name: Build produdction app and store build
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checking out repository...
        uses: actions/checkout@v3

      - id: node
        name: Setting up node v16...
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: store build
          path: |
            build
