# Deploy to Netlify Prod
name: Trigger production deployment in Netlify

on: workflow_dispatch

jobs:
  job:
    name: (Job) Trigger production deployment in Netlify
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK_TOKEN }}
